In [1]:
import torch
from torchvision import datasets
from torch.utils.data import DataLoader
from torchvision import transforms
import numpy as np
from utilsCPD import *
import matplotlib.pyplot as plt
from SWCPD import BaseDetector as SWDCP


BATCH_SIZE  =32
mnist_transforms = transforms.Compose([transforms.ToTensor()])
train_val_dataset = datasets.MNIST(root="./datasets/", train=True, download=True, transform=mnist_transforms)
test_dataset = datasets.MNIST(root="./datasets/", train=False, download=True, transform=mnist_transforms)
train_size = int(0.9 * len(train_val_dataset))
val_size = len(train_val_dataset) - train_size
train_dataset, val_dataset = torch.utils.data.random_split(dataset=train_val_dataset, lengths=[train_size, val_size])
train_dataloader = DataLoader(dataset=train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_dataloader = DataLoader(dataset=val_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_dataloader = DataLoader(dataset=test_dataset, batch_size=BATCH_SIZE, shuffle=True)

In [2]:
all_batches = []
all_labels =[]
torch.manual_seed(10)
for x,y in test_dataloader:
    bs = x.shape[0]
    all_batches.append(x.flatten().reshape(bs,784))
    all_labels.append(y)

all_batches = torch.cat(all_batches,dim=0)
all_labels = torch.cat(all_labels,dim=0)

print(all_batches.shape)

torch.Size([10000, 784])


In [3]:
Labels_Sampled = []
seed = 2025
rng = np.random.default_rng(seed)


def sample_classes(seed,n_classes = 3,nb_experiments=5):
    rng = np.random.default_rng(seed)
    Labels_Sampled = []
    for run in range(nb_experiments):
        l = tuple(rng.choice(np.arange(10),n_classes,replace=False))
        if l not in Labels_Sampled:
            Labels_Sampled.append(l)
    return Labels_Sampled

Labels_Sampled = sample_classes(seed=seed, n_classes=3,nb_experiments=5)

print(Labels_Sampled)
def FilterData(all_batches,all_labels,lables,N_Samples=200):
    data = []
    cps = []
    for l in lables:
        d =all_batches[all_labels==l].detach().numpy()
        data.append(d[:N_Samples])
        cps.append(len(d[:N_Samples]))
    return np.vstack(data),np.cumsum(cps)[:-1]


FilterData(all_batches,all_labels,list(Labels_Sampled[0]))


[(3, 9, 8), (6, 5, 8), (0, 4, 3), (6, 7, 8), (4, 3, 0)]


(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([200, 400]))

In [64]:
LABELS_Sampled = [sample_classes(seed=seed,n_classes=3,nb_experiments=5),sample_classes(seed=seed, n_classes=4,nb_experiments=5),sample_classes(seed=seed, n_classes=5,nb_experiments=5)]
LABELS_Sampled

[[(3, 9, 8), (6, 5, 8), (0, 4, 3), (6, 7, 8), (4, 3, 0)],
 [(3, 7, 8, 9), (8, 3, 6, 5), (7, 6, 3, 8), (8, 7, 3, 2), (6, 7, 4, 2)],
 [(2, 6, 3, 7, 9),
  (5, 2, 3, 4, 0),
  (4, 0, 3, 8, 2),
  (4, 6, 7, 0, 2),
  (0, 1, 9, 3, 2)]]

In [23]:
METRICS_SWD = {}
Data_OUT = {}
LABELS_Sampled = [sample_classes(seed=seed,n_classes=3,nb_experiments=5),sample_classes(seed=seed, n_classes=4,nb_experiments=5),sample_classes(seed=seed, n_classes=5,nb_experiments=5)]
ind = 0
ind2 = 0
LABELS_Sampled
for id,i in enumerate(range(15)):
    print(id)
    Data_OUT[id] = {}
    METRICS_SWD[id]  = {}
    if i in [5,10]:
        ind+=1
        ind2 = 0
    df, GroundTruth = FilterData(all_batches,all_labels,list(LABELS_Sampled[ind][ind2]),N_Samples=200)
    Data_OUT[id]['data'] = df
    Data_OUT[id]['target'] = GroundTruth
    ind2+=1
    print(GroundTruth)
    detector = SWDCP(data=df,window_length=50,max_history=50,significance=0.05)
    print(detector.device)
    detector.process_dataloader(p=4,n_theta=5000,seed=2025)
    f1, covering_score, auc_score = detector.evaluate(GroundTruth,20)
    METRICS_SWD[id]['F1'] = f1
    METRICS_SWD[id]['Covering'] = covering_score
    METRICS_SWD[id]['AUC'] = auc_score
    print(METRICS_SWD[id])

0
[200 400]
cuda


 31%|███▏      | 173/551 [00:04<00:09, 38.67it/s]

Change detected at: 216 
Initiate new segment


 68%|██████▊   | 376/551 [00:09<00:04, 36.78it/s]

Change detected at: 420 
Initiate new segment


100%|██████████| 551/551 [00:14<00:00, 38.24it/s]


F1 score: 1.0
Covering: 0.8874298540965208
1.0
{'F1': 1.0, 'Covering': 0.8874298540965208, 'AUC': 1.0}
1
[200 400]
cuda


 31%|███       | 170/551 [00:04<00:09, 39.41it/s]

Change detected at: 215 
Initiate new segment


100%|██████████| 551/551 [00:13<00:00, 39.64it/s]


F1 score: 0.8
Covering: 0.6374043592066848
0.8333333333333333
{'F1': 0.8, 'Covering': 0.6374043592066848, 'AUC': 0.8333333333333333}
2
[200 400]
cuda


 31%|███       | 171/551 [00:04<00:09, 41.05it/s]

Change detected at: 214 
Initiate new segment


 67%|██████▋   | 367/551 [00:09<00:04, 40.04it/s]

Change detected at: 412 
Initiate new segment


100%|██████████| 551/551 [00:13<00:00, 40.45it/s]


F1 score: 1.0
Covering: 0.9173126432727914
1.0
{'F1': 1.0, 'Covering': 0.9173126432727914, 'AUC': 1.0}
3
[200 400]
cuda


 31%|███       | 170/551 [00:04<00:09, 41.00it/s]

Change detected at: 212 
Initiate new segment


 68%|██████▊   | 375/551 [00:09<00:04, 42.93it/s]

Change detected at: 416 
Initiate new segment


 71%|███████   | 390/551 [00:09<00:03, 42.15it/s]

Change detected at: 431 
Initiate new segment


100%|██████████| 551/551 [00:13<00:00, 41.27it/s]


F1 score: 0.8571428571428571
Covering: 0.8862555322618216
0.875
{'F1': 0.8571428571428571, 'Covering': 0.8862555322618216, 'AUC': 0.875}
4
[200 400]
cuda


 31%|███       | 169/551 [00:04<00:08, 42.87it/s]

Change detected at: 212 
Initiate new segment


 66%|██████▌   | 364/551 [00:08<00:04, 40.35it/s]

Change detected at: 408 
Initiate new segment


100%|██████████| 551/551 [00:13<00:00, 41.47it/s]


F1 score: 1.0
Covering: 0.9357474600870826
1.0
{'F1': 1.0, 'Covering': 0.9357474600870826, 'AUC': 1.0}
5
[200 400 600]
cuda


 22%|██▏       | 164/751 [00:03<00:14, 41.03it/s]

Change detected at: 210 
Initiate new segment


 50%|████▉     | 372/751 [00:09<00:09, 39.81it/s]

Change detected at: 416 
Initiate new segment


 52%|█████▏    | 388/751 [00:09<00:09, 37.03it/s]

Change detected at: 431 
Initiate new segment


 78%|███████▊  | 583/751 [00:14<00:04, 39.78it/s]

Change detected at: 625 
Initiate new segment


100%|██████████| 751/751 [00:18<00:00, 40.02it/s]


F1 score: 0.6666666666666665
Covering: 0.8645304232804232
0.675
{'F1': 0.6666666666666665, 'Covering': 0.8645304232804232, 'AUC': 0.675}
6
[200 400 600]
cuda


 23%|██▎       | 174/751 [00:04<00:14, 39.35it/s]

Change detected at: 218 
Initiate new segment
Change detected at: 220 
Initiate new segment


 48%|████▊     | 363/751 [00:09<00:09, 39.05it/s]

Change detected at: 409 
Initiate new segment


 76%|███████▋  | 574/751 [00:14<00:04, 43.11it/s]

Change detected at: 615 
Initiate new segment


100%|██████████| 751/751 [00:18<00:00, 39.91it/s]


F1 score: 0.888888888888889
Covering: 0.8980118262056405
0.9
{'F1': 0.888888888888889, 'Covering': 0.8980118262056405, 'AUC': 0.9}
7
[200 400 600]
cuda


 23%|██▎       | 169/751 [00:04<00:13, 43.91it/s]

Change detected at: 212 
Initiate new segment


 49%|████▉     | 369/751 [00:08<00:08, 42.53it/s]

Change detected at: 414 
Initiate new segment


 76%|███████▌  | 572/751 [00:14<00:04, 39.53it/s]

Change detected at: 617 
Initiate new segment


100%|██████████| 751/751 [00:18<00:00, 40.60it/s]


F1 score: 1.0
Covering: 0.898510939113787
1.0
{'F1': 1.0, 'Covering': 0.898510939113787, 'AUC': 1.0}
8
[200 400 600]
cuda


 23%|██▎       | 176/751 [00:04<00:14, 40.95it/s]

Change detected at: 220 
Initiate new segment


 50%|████▉     | 373/751 [00:09<00:09, 40.93it/s]

Change detected at: 415 
Initiate new segment


 76%|███████▌  | 572/751 [00:14<00:04, 42.08it/s]

Change detected at: 615 
Initiate new segment


100%|██████████| 751/751 [00:18<00:00, 40.32it/s]


F1 score: 1.0
Covering: 0.8829413319238901
1.0
{'F1': 1.0, 'Covering': 0.8829413319238901, 'AUC': 1.0}
9
[200 400 600]
cuda


 23%|██▎       | 170/751 [00:04<00:14, 39.36it/s]

Change detected at: 212 
Initiate new segment


 51%|█████     | 380/751 [00:09<00:08, 42.09it/s]

Change detected at: 422 
Initiate new segment
Change detected at: 424 
Initiate new segment


 76%|███████▌  | 570/751 [00:14<00:04, 41.47it/s]

Change detected at: 614 
Initiate new segment


100%|██████████| 751/751 [00:18<00:00, 40.75it/s]


F1 score: 0.6666666666666665
Covering: 0.8856682449509993
0.675
{'F1': 0.6666666666666665, 'Covering': 0.8856682449509993, 'AUC': 0.675}
10
[200 400 600 800]
cuda


 19%|█▊        | 177/951 [00:04<00:20, 38.53it/s]

Change detected at: 221 
Initiate new segment


 39%|███▉      | 373/951 [00:09<00:13, 42.98it/s]

Change detected at: 414 
Initiate new segment


 60%|█████▉    | 566/951 [00:13<00:09, 40.99it/s]

Change detected at: 610 
Initiate new segment


100%|██████████| 951/951 [00:23<00:00, 40.97it/s]


F1 score: 0.6666666666666665
Covering: 0.7229921544462501
0.675
{'F1': 0.6666666666666665, 'Covering': 0.7229921544462501, 'AUC': 0.675}
11
[200 400 600 800]
cuda


 19%|█▉        | 179/951 [00:04<00:17, 44.08it/s]

Change detected at: 220 
Initiate new segment


 19%|█▉        | 184/951 [00:04<00:18, 41.69it/s]

Change detected at: 230 
Initiate new segment


 40%|███▉      | 379/951 [00:09<00:14, 40.35it/s]

Change detected at: 420 
Initiate new segment


 60%|█████▉    | 569/951 [00:13<00:08, 44.21it/s]

Change detected at: 610 
Initiate new segment


 80%|████████  | 764/951 [00:18<00:04, 42.30it/s]

Change detected at: 809 
Initiate new segment


100%|██████████| 951/951 [00:22<00:00, 42.31it/s]


F1 score: 0.9090909090909091
Covering: 0.8806103896103896
0.9166666666666667
{'F1': 0.9090909090909091, 'Covering': 0.8806103896103896, 'AUC': 0.9166666666666667}
12
[200 400 600 800]
cuda


 18%|█▊        | 167/951 [00:04<00:17, 43.58it/s]

Change detected at: 209 
Initiate new segment


 39%|███▉      | 372/951 [00:08<00:13, 41.87it/s]

Change detected at: 413 
Initiate new segment


 60%|██████    | 571/951 [00:13<00:09, 41.28it/s]

Change detected at: 617 
Initiate new segment


 82%|████████▏ | 777/951 [00:18<00:04, 41.72it/s]

Change detected at: 818 
Initiate new segment


100%|██████████| 951/951 [00:22<00:00, 41.68it/s]


F1 score: 1.0
Covering: 0.8929704214849346
1.0
{'F1': 1.0, 'Covering': 0.8929704214849346, 'AUC': 1.0}
13
[200 400 600 800]
cuda


 18%|█▊        | 174/951 [00:04<00:18, 42.06it/s]

Change detected at: 218 
Initiate new segment


 39%|███▉      | 369/951 [00:08<00:13, 42.47it/s]

Change detected at: 412 
Initiate new segment


 60%|█████▉    | 569/951 [00:13<00:08, 42.55it/s]

Change detected at: 610 
Initiate new segment


 81%|████████  | 768/951 [00:18<00:04, 41.13it/s]

Change detected at: 813 
Initiate new segment


100%|██████████| 951/951 [00:22<00:00, 42.28it/s]


F1 score: 1.0
Covering: 0.8996357266558209
1.0
{'F1': 1.0, 'Covering': 0.8996357266558209, 'AUC': 1.0}
14
[200 400 600 800]
cuda


 17%|█▋        | 166/951 [00:03<00:18, 41.58it/s]

Change detected at: 210 
Initiate new segment


 38%|███▊      | 366/951 [00:08<00:13, 42.14it/s]

Change detected at: 409 
Initiate new segment


 60%|█████▉    | 570/951 [00:13<00:08, 43.92it/s]

Change detected at: 615 
Initiate new segment


 81%|████████  | 770/951 [00:17<00:04, 43.64it/s]

Change detected at: 815 
Initiate new segment


100%|██████████| 951/951 [00:22<00:00, 42.92it/s]

F1 score: 1.0
Covering: 0.9070618141548373
1.0
{'F1': 1.0, 'Covering': 0.9070618141548373, 'AUC': 1.0}


In [24]:
f1,cov, AUC = [],[],[]
for k,metrics in METRICS_SWD.items():
    f1.append(metrics['F1'])
    cov.append(metrics['Covering'])
    AUC.append(metrics['AUC'])


#print(np.mean(f1))
print(np.mean(cov))
print(np.mean(AUC))

0.8664722080501247
0.9033333333333334


In [ ]:
# import json

# class NumpyEncoder(json.JSONEncoder):
#     def default(self, obj):
#         if isinstance(obj, np.ndarray):
#             return obj.tolist()
#         return super().default(obj)
    
# with open('data.json', 'w', encoding='utf-8') as f:
#     json.dump(Data_OUT, f, ensure_ascii=False, indent=4,cls=NumpyEncoder)

In [ ]:
from claspy.segmentation import BinaryClaSPSegmentation
ind = 0
ind2 = 0
METRICS_Claspy = {}
for id,i in enumerate(range(15)):
    print(id)
    METRICS_Claspy[id]  = {}
    if i in [5,10]:
        ind+=1
        ind2 = 0
    df, GroundTruth = FilterData(all_batches,all_labels,list(LABELS_Sampled[ind][ind2]),N_Samples=200)
    ind2+=1
    print(GroundTruth)
    clasp = BinaryClaSPSegmentation(window_size=100).fit(df.astype(np.float64))
    f1,auc_score = f_measure({'0':GroundTruth},clasp.change_points,20)
    covering_score = covering({'0':GroundTruth},clasp.change_points,df.shape[0])
    METRICS_Claspy[id]['F1'] = f1
    METRICS_Claspy[id]['Covering'] = covering_score
    METRICS_Claspy[id]['AUC'] = auc_score
    print(METRICS_Claspy[id])

In [54]:
f1,cov, AUC = [],[],[]
for k,metrics in METRICS_Claspy.items():
    f1.append(metrics['F1'])
    cov.append(metrics['Covering'])
    AUC.append(metrics['AUC'])
print(np.std(cov))
print(np.std(AUC))

0.05499719409228699
0.027498597046143512


In [21]:
data_out = {}
ind2=0
ind=0
for id,i in enumerate(range(15)):
    if i in [5,10]:
        ind+=1
        ind2 = 0
    df, GroundTruth = FilterData(all_batches,all_labels,list(LABELS_Sampled[ind][ind2]),N_Samples=200)
    data_out[id] = {'data':df,'labels':GroundTruth}

In [22]:
# import json

# class NumpyEncoder(json.JSONEncoder):
#     def default(self, obj):
#         if isinstance(obj, np.ndarray):
#             return obj.tolist()
#         return super().default(obj)
    
# with open('data.json', 'w', encoding='utf-8') as f:
#     json.dump(data_out, f, ensure_ascii=False, indent=4,cls=NumpyEncoder)

### Results for E-divisive and BOCPD

In [48]:
import json

with open("./R/res//MNIST_Edivise.json") as f:
    ECP_Results = json.load(f)


F1,Covering, AUC = [],[],[]

for id, cps in ECP_Results.items():
    ground_truths = data_out[int(id)]['labels']
    n = ground_truths[-1] + 200
    cps = cps[1:-1]

    f1, AUC_score = f_measure({'0':ground_truths},cps,20)
    covering_score = covering({'0':ground_truths},cps,n)
    F1.append(f1)
    AUC.append(AUC_score)
    Covering.append(covering_score)

print(np.mean(F1))
print(np.std(Covering))
print(np.std(AUC))

0.9569023569023568
0.05164545795524169
0.047790695928014576


In [51]:
with open("./R/res/MNIST_BOCPD.json") as f:
    ECP_Results = json.load(f)


F1,Covering, AUC = [],[],[]

for id, cps in ECP_Results.items():
    #print(cps)
    ground_truths = data_out[int(id)]['labels']
    n = ground_truths[-1] + 200
    cps = cps[0][1:]
    #print(cps)
    f1, AUC_score = f_measure({'0':ground_truths},cps,20)
    covering_score = covering({'0':ground_truths},cps,n)
    F1.append(f1)
    AUC.append(AUC_score)
    #print(AUC_score)
    Covering.append(covering_score)

print(np.mean(F1))
print(np.mean(Covering))
print(np.mean(AUC))

0.6844444444444445
0.7847463171351448
0.6916666666666668
